/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as MypetIndexRouteImport } from './routes/mypet/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LandingIndexRouteImport } from './routes/landing/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as ProfileCouponRouteImport } from './routes/profile/coupon'
import { Route as MypetQuestRouteImport } from './routes/mypet/quest'
import { Route as MypetDiaryRouteImport } from './routes/mypet/diary'
import { Route as LoginCheckPermissionRouteImport } from './routes/login/checkPermission'
import { Route as LandingCafeRouteImport } from './routes/landing/cafe'
import { Route as PlacePlaceIdReviewRouteImport } from './routes/place/$placeId/review'

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const MypetIndexRoute = MypetIndexRouteImport.update({
  id: '/mypet/',
  path: '/mypet/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCouponRoute = ProfileCouponRouteImport.update({
  id: '/profile/coupon',
  path: '/profile/coupon',
  getParentRoute: () => rootRouteImport,
} as any)
const MypetQuestRoute = MypetQuestRouteImport.update({
  id: '/mypet/quest',
  path: '/mypet/quest',
  getParentRoute: () => rootRouteImport,
} as any)
const MypetDiaryRoute = MypetDiaryRouteImport.update({
  id: '/mypet/diary',
  path: '/mypet/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCheckPermissionRoute = LoginCheckPermissionRouteImport.update({
  id: '/login/checkPermission',
  path: '/login/checkPermission',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingCafeRoute = LandingCafeRouteImport.update({
  id: '/landing/cafe',
  path: '/landing/cafe',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacePlaceIdReviewRoute = PlacePlaceIdReviewRouteImport.update({
  id: '/place/$placeId/review',
  path: '/place/$placeId/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/landing/cafe': typeof LandingCafeRoute
  '/login/checkPermission': typeof LoginCheckPermissionRoute
  '/mypet/diary': typeof MypetDiaryRoute
  '/mypet/quest': typeof MypetQuestRoute
  '/profile/coupon': typeof ProfileCouponRoute
  '/cart': typeof CartIndexRoute
  '/landing': typeof LandingIndexRoute
  '/login': typeof LoginIndexRoute
  '/mypet': typeof MypetIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/place/$placeId/review': typeof PlacePlaceIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/landing/cafe': typeof LandingCafeRoute
  '/login/checkPermission': typeof LoginCheckPermissionRoute
  '/mypet/diary': typeof MypetDiaryRoute
  '/mypet/quest': typeof MypetQuestRoute
  '/profile/coupon': typeof ProfileCouponRoute
  '/cart': typeof CartIndexRoute
  '/landing': typeof LandingIndexRoute
  '/login': typeof LoginIndexRoute
  '/mypet': typeof MypetIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/place/$placeId/review': typeof PlacePlaceIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/landing/cafe': typeof LandingCafeRoute
  '/login/checkPermission': typeof LoginCheckPermissionRoute
  '/mypet/diary': typeof MypetDiaryRoute
  '/mypet/quest': typeof MypetQuestRoute
  '/profile/coupon': typeof ProfileCouponRoute
  '/cart/': typeof CartIndexRoute
  '/landing/': typeof LandingIndexRoute
  '/login/': typeof LoginIndexRoute
  '/mypet/': typeof MypetIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/place/$placeId/review': typeof PlacePlaceIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/landing/cafe'
    | '/login/checkPermission'
    | '/mypet/diary'
    | '/mypet/quest'
    | '/profile/coupon'
    | '/cart'
    | '/landing'
    | '/login'
    | '/mypet'
    | '/profile'
    | '/place/$placeId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/landing/cafe'
    | '/login/checkPermission'
    | '/mypet/diary'
    | '/mypet/quest'
    | '/profile/coupon'
    | '/cart'
    | '/landing'
    | '/login'
    | '/mypet'
    | '/profile'
    | '/place/$placeId/review'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/landing/cafe'
    | '/login/checkPermission'
    | '/mypet/diary'
    | '/mypet/quest'
    | '/profile/coupon'
    | '/cart/'
    | '/landing/'
    | '/login/'
    | '/mypet/'
    | '/profile/'
    | '/place/$placeId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  LandingCafeRoute: typeof LandingCafeRoute
  LoginCheckPermissionRoute: typeof LoginCheckPermissionRoute
  MypetDiaryRoute: typeof MypetDiaryRoute
  MypetQuestRoute: typeof MypetQuestRoute
  ProfileCouponRoute: typeof ProfileCouponRoute
  CartIndexRoute: typeof CartIndexRoute
  LandingIndexRoute: typeof LandingIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MypetIndexRoute: typeof MypetIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  PlacePlaceIdReviewRoute: typeof PlacePlaceIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypet/': {
      id: '/mypet/'
      path: '/mypet'
      fullPath: '/mypet'
      preLoaderRoute: typeof MypetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/': {
      id: '/landing/'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/coupon': {
      id: '/profile/coupon'
      path: '/profile/coupon'
      fullPath: '/profile/coupon'
      preLoaderRoute: typeof ProfileCouponRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypet/quest': {
      id: '/mypet/quest'
      path: '/mypet/quest'
      fullPath: '/mypet/quest'
      preLoaderRoute: typeof MypetQuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypet/diary': {
      id: '/mypet/diary'
      path: '/mypet/diary'
      fullPath: '/mypet/diary'
      preLoaderRoute: typeof MypetDiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/checkPermission': {
      id: '/login/checkPermission'
      path: '/login/checkPermission'
      fullPath: '/login/checkPermission'
      preLoaderRoute: typeof LoginCheckPermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/cafe': {
      id: '/landing/cafe'
      path: '/landing/cafe'
      fullPath: '/landing/cafe'
      preLoaderRoute: typeof LandingCafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$placeId/review': {
      id: '/place/$placeId/review'
      path: '/place/$placeId/review'
      fullPath: '/place/$placeId/review'
      preLoaderRoute: typeof PlacePlaceIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  LandingCafeRoute: LandingCafeRoute,
  LoginCheckPermissionRoute: LoginCheckPermissionRoute,
  MypetDiaryRoute: MypetDiaryRoute,
  MypetQuestRoute: MypetQuestRoute,
  ProfileCouponRoute: ProfileCouponRoute,
  CartIndexRoute: CartIndexRoute,
  LandingIndexRoute: LandingIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MypetIndexRoute: MypetIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  PlacePlaceIdReviewRoute: PlacePlaceIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
