/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LandingIndexRouteImport } from './routes/landing/index'
import { Route as LoginCheckPermissionRouteImport } from './routes/login/checkPermission'
import { Route as LandingCafeRouteImport } from './routes/landing/cafe'
import { Route as PlacePlaceIdReviewRouteImport } from './routes/place/$placeId/review'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCheckPermissionRoute = LoginCheckPermissionRouteImport.update({
  id: '/login/checkPermission',
  path: '/login/checkPermission',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingCafeRoute = LandingCafeRouteImport.update({
  id: '/landing/cafe',
  path: '/landing/cafe',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacePlaceIdReviewRoute = PlacePlaceIdReviewRouteImport.update({
  id: '/place/$placeId/review',
  path: '/place/$placeId/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/landing/cafe': typeof LandingCafeRoute
  '/login/checkPermission': typeof LoginCheckPermissionRoute
  '/landing': typeof LandingIndexRoute
  '/login': typeof LoginIndexRoute
  '/place/$placeId/review': typeof PlacePlaceIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/landing/cafe': typeof LandingCafeRoute
  '/login/checkPermission': typeof LoginCheckPermissionRoute
  '/landing': typeof LandingIndexRoute
  '/login': typeof LoginIndexRoute
  '/place/$placeId/review': typeof PlacePlaceIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/landing/cafe': typeof LandingCafeRoute
  '/login/checkPermission': typeof LoginCheckPermissionRoute
  '/landing/': typeof LandingIndexRoute
  '/login/': typeof LoginIndexRoute
  '/place/$placeId/review': typeof PlacePlaceIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/landing/cafe'
    | '/login/checkPermission'
    | '/landing'
    | '/login'
    | '/place/$placeId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/landing/cafe'
    | '/login/checkPermission'
    | '/landing'
    | '/login'
    | '/place/$placeId/review'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/landing/cafe'
    | '/login/checkPermission'
    | '/landing/'
    | '/login/'
    | '/place/$placeId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  LandingCafeRoute: typeof LandingCafeRoute
  LoginCheckPermissionRoute: typeof LoginCheckPermissionRoute
  LandingIndexRoute: typeof LandingIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  PlacePlaceIdReviewRoute: typeof PlacePlaceIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/': {
      id: '/landing/'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/checkPermission': {
      id: '/login/checkPermission'
      path: '/login/checkPermission'
      fullPath: '/login/checkPermission'
      preLoaderRoute: typeof LoginCheckPermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/cafe': {
      id: '/landing/cafe'
      path: '/landing/cafe'
      fullPath: '/landing/cafe'
      preLoaderRoute: typeof LandingCafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$placeId/review': {
      id: '/place/$placeId/review'
      path: '/place/$placeId/review'
      fullPath: '/place/$placeId/review'
      preLoaderRoute: typeof PlacePlaceIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  LandingCafeRoute: LandingCafeRoute,
  LoginCheckPermissionRoute: LoginCheckPermissionRoute,
  LandingIndexRoute: LandingIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  PlacePlaceIdReviewRoute: PlacePlaceIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
